# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'covid19-dashboard-swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for covid19-dashboard-swift
  pod 'Charts'

end
